# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1874b625e3ffd1ddf7f0788641d15e4c18f0170b94d60e5ad7021672190f092b33356525004857164811b01f6415b36668404ae0cf4e17bd72a8527795c09661

test:
  secret_key_base: 556b7b3e011ac84c9d1251b410035bd99d7147292ec46bcd579a0ddb23cd29a40654a1ce7ff82544e8404559d0683b6247c73a4f329329be9eefac7762ed56ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
